// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using eStoreCA.Infrastructure.Data;

#nullable disable

namespace eStoreCA.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250528044153_Seeding Data")]
    partial class SeedingData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.AppClaim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ClaimTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLink")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlLink")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("AppClaims");
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.AuditTrailLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ActionDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("AffectedColumns")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NewValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValues")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PrimaryKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("AuditTrailLogs");
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.Category", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("Id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("CreatedAt");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("CreatedBy");

                    b.Property<DateTime?>("DeletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("DeletedAt");

                    b.Property<Guid?>("DeletedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("DeletedBy");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("IsActive");

                    b.Property<DateTime?>("LastModifiedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("LastModifiedAt");

                    b.Property<Guid?>("LastModifiedBy")
                        .HasColumnType("uniqueidentifier")
                        .HasColumnName("LastModifiedBy");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion")
                        .HasColumnName("RowVersion");

                    b.Property<bool>("SoftDeleted")
                        .HasColumnType("bit")
                        .HasColumnName("SoftDeleted");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)")
                        .HasColumnName("Title");

                    b.HasKey("Id");

                    b.HasIndex("SoftDeleted");

                    b.ToTable("Categories", "dbo");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000001"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Electronics"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000002"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Clothing"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000003"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Footwear"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000004"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Home & Kitchen"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000005"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Beauty & Personal Care"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000006"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Books"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000007"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Health & Wellness"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000008"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Toys & Games"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000009"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Jewelry"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000010"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Watches"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000011"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Sports & Outdoors"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000012"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Automotive"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000013"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Furniture"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000014"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Office Supplies"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000015"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Pet Supplies"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000016"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Baby Products"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000017"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Garden & Outdoors"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000018"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Tools & Hardware"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000019"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Musical Instruments"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000020"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Groceries"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000021"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Stationery"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000022"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Travel Accessories"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000023"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Bags & Luggage"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000024"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Mobile Accessories"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000025"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Camera & Photography"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000026"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Smart Home Devices"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000027"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Kitchen Appliances"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000028"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Cleaning Supplies"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000029"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Bath Accessories"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000030"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "DIY & Crafts"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000031"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Gaming"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000032"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Nutrition & Supplements"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000033"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Lighting"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000034"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Home Decor"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000035"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Wall Art"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000036"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Curtains & Blinds"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000037"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Mattresses & Bedding"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000038"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Event & Party Supplies"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000039"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Costumes & Accessories"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000040"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Seasonal Décor"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000041"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Green & Eco Products"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000042"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Industrial Supplies"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000043"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Safety & Security"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000044"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Lab & Scientific Supplies"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000045"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Collectibles"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000046"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Antiques"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000047"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Luxury Goods"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000048"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Digital Products"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000049"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "Subscription Boxes"
                        },
                        new
                        {
                            Id = new Guid("a1111111-1111-1111-1111-000000000050"),
                            CreatedAt = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            CreatedBy = new Guid("11111111-1111-1111-1111-111111111111"),
                            IsActive = true,
                            SoftDeleted = false,
                            Title = "3D Printing Supplies"
                        });
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.LogUserActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Browser")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IPAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("ImpersonatedBy")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UrlData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserData")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.ToTable("LogUserActivities");
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<Guid>("ApplicationUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ExpiresOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RevokedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("eStoreCA.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("eStoreCA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("eStoreCA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("eStoreCA.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("eStoreCA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("eStoreCA.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.AppClaim", b =>
                {
                    b.HasOne("eStoreCA.Domain.Entities.AppClaim", "Parent")
                        .WithMany("AppClaims")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("eStoreCA.Domain.Entities.AppClaim", b =>
                {
                    b.Navigation("AppClaims");
                });
#pragma warning restore 612, 618
        }
    }
}
